title: <p align="center"> Mamta Khubchandani </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mamta-khubchandani-5665bb130">LinkedIn</a> |
  <a href="https://github.com/MamtaK5">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
 
  <br>
  </p>
